### ISSUE TITLE
waveform display

### ISSUE THREAD

**Issue by gunbat-dev** [mmahdim/stm32f4scope#2]
Hello!
I'm trying to implement an oscilloscope on the STM32F407. ADC 1,2,3 in triple mode, 7.2Mbps.
Display 240x320 ili9341 fsmc
I'm sending a signal from the generator. A pure sine wave is obtained only at certain frequencies. At other frequencies there are some chaos fragments. What can be done to solve it? I can make a video.

Best regards,
Sergey

**Comment by mmahdim** [comment]
Hello Sergey,
I didn't quite understand. Are you trying to implement my code, or are you developing your own project from scratch?
My best guess is that your triggering has problems.
Best,
Mahdi

**Comment by gunbat-dev** [comment]
Hello Mahdi,
I trying to developing my own project. And I think you right, that this is a trigger, but mabe something else. I just set adc 1,2,3 to triple mode, dma in circular mode, and try to view waveform on display. Maybe you take a look at this link: https://disk.yandex.ru/i/vYFP8YcS9oSo8g
https://disk.yandex.ru/i/lMUaabJM9Gc2Bg

Best regards,
Sergey

**Comment by mmahdim** [comment]
It's really hard to tell without seeing the code, and unfortunately, I don't have the time to review your code.
But it seems like a trigger issue to me. You can check my code to see the way that I implemented my triggering. I think it was using a GPIO pin as an interrupt. I hope you can figure it out.
Best,
Mahdi

**Comment by gunbat-dev** [comment]
OK. Thank you!
